<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIzLWjB\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIzLWjB/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSIzLWjB.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSIzLWjB\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerSIzLWjB\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'SIzLWjB',
    'container.build_id' => 'd6226f99',
    'container.build_time' => 1523809019,
));
