<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK309oxr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK309oxr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK309oxr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK309oxr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerK309oxr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'K309oxr',
    'container.build_id' => 'b893abff',
    'container.build_time' => 1523889948,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK309oxr');
